Feature/login implementation
RPUruIT/WhoIs pull request #1
Opened 2017-11-28 20:09 UTC by RPUruIT

2017-11-28 20:42 UTC, adrianclaveri requested changes

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/Test/UnitTest1.cs
> +    public class UnitTest1
Esta clase no va

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Managers/AppUserManager.cs
> +            return new Object[2] { userForApplication, allUsers };
Porque un array con 2 listas? son necesarias las 2? puede ser un objeto tipado?

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Managers/AppUserManager.cs
> +        public async Task EnterToApplication(AppUser appUser)
Esto seria el login?

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Models/AppUser.cs
> +        protected string ExternalId
Se puede abreviar el get set.

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Repositories/AppUserRepository.cs
> +            AppUser appUser = await _database.GetFirst();
Si te logueas con 2 usuarios distintos, te devuelve siempre el primero?

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Repositories/Database.cs
> +            return await Task.Run(() => _database.Insert(entity));
Estaria bueno usar los inserts async derecho

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Repositories/Interface/IUserToHuntRepository.cs
> +    public interface IUserToHuntRepository
Por que hay una interface vacia?

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Services/ServiceMOC.cs
> +            await Task.Run(null);
evitar el uso de run null

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/ViewModels/BaseViewModel.cs
> +            _appUserManager = DependencyContainer.Container.Resolve<IAppUserManager>();
Al agregar el appUserManager en el baseviewmodel, queda disponible para todos los viemodels, cosa que no seria correcto. Mas alla de que no hay problemas de dependencia, se esta agregando una sin necesidad.

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/ViewModels/LoginViewModel.cs
> +            }
Si no selecciono ningun usuario que pasa? tengo feedback en la vista?

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Views/CustomNavigationView.xaml
> +    <ContentPage.Content>
Esto no es necesario

2017-11-28 20:42 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Views/LoginView.xaml
> +                <Label Text="{Binding AppName}" HorizontalOptions="Center" FontSize="40" TextColor="{StaticResource WhiteColor}}" FontFamily="{StaticResource Pacifico-Regular}"></Label>
Se pueden pasar los estilos al diccionario, para que sea mas facil de leer y sea reutilizable

2017-11-29 11:51 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Models/AppUser.cs
> +        protected string ExternalId
si, esto me lo genero con el propfull tab tab

2017-11-29 11:53 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Repositories/AppUserRepository.cs
> +            AppUser appUser = await _database.GetFirst();
Lo pense como que al deslogearse el usuario, lo borraba de la base,, osea solo tendria un unico usuario almacenado

2017-11-29 11:54 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Repositories/Database.cs
> +            return await Task.Run(() => _database.Insert(entity));
A bien, esta clase la copie directamente de la de kardia, lo cambio

2017-11-29 11:56 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Repositories/Interface/IUserToHuntRepository.cs
> +    public interface IUserToHuntRepository
La voy a implementar luego para manejar los usuarios capturados con la camara

2017-11-29 11:57 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Services/ServiceMOC.cs
> +            await Task.Run(null);
Oks perfecto, lo cambio.

2017-11-29 11:59 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/ViewModels/BaseViewModel.cs
> +            _appUserManager = DependencyContainer.Container.Resolve<IAppUserManager>();
Si, es cierto, lo habia pensado por si tenia que ir a buscar el usuario desde cualquiera de los viewmodels u hacer alguna operacion relacionada con el usuario logeado. Luego me comentaste el pique de almacenar el usuario en la clase App asi que lo saco.

2017-11-29 12:03 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/ViewModels/LoginViewModel.cs
> +            }
Es cierto, podria tirarle un mensajito, pero tal vez lo podría dejar para mas adelante o como te parezca.

2017-11-29 12:03 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Views/CustomNavigationView.xaml
> +    <ContentPage.Content>
Ponerle NavigationPage? o el ContentPage.Content?

2017-11-29 12:05 UTC, RPUruIT commented on WhoIs/WhoIs/WhoIs/Views/LoginView.xaml
> +                <Label Text="{Binding AppName}" HorizontalOptions="Center" FontSize="40" TextColor="{StaticResource WhiteColor}}" FontFamily="{StaticResource Pacifico-Regular}"></Label>
Si, acá lo que senti que era reutilizable lo puse en el diccionario, lo que me parecia propio de esta vista como los HorizontalOptions=Center y algun margin en particular y eso, los meti ahi directamente.

2017-11-29 12:58 UTC, adrianclaveri requested changes

2017-11-29 12:58 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Repositories/AppUserRepository.cs
> +            AppUser appUser = await _database.GetFirst();
Mas que nada pensar en que pasa si se llama al codigo y no hay nada en la BD. Creo que GetFirst si no hay nada tira exception, el GetFirstOrDefault retorna nulo y es mejor de manejar.

2017-11-29 12:58 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Repositories/Interface/IUserToHuntRepository.cs
> +    public interface IUserToHuntRepository
Esta bueno si queda algo colgado o codigo comentado para hacer despues, ponerle un //TODO: Asi queda mas facil de buscar e indica que faltan cosas

2017-11-29 12:58 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/ViewModels/LoginViewModel.cs
> +            }
Ver comentario de //TODO: arriba. Si dejas el mensaje para despues, agregalo a otra historia x las dudas.

2017-11-29 12:58 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Views/CustomNavigationView.xaml
> +    <ContentPage.Content>
El ContentPage.Content, xq esta vacio

2017-11-29 12:58 UTC, adrianclaveri commented on WhoIs/WhoIs/WhoIs/Views/LoginView.xaml
> +                <Label Text="{Binding AppName}" HorizontalOptions="Center" FontSize="40" TextColor="{StaticResource WhiteColor}}" FontFamily="{StaticResource Pacifico-Regular}"></Label>
Claro, lo reutilizable se puede poner en el diccionario del app.cs, lo que es propio de la vista en un diccionario en la vista mismo. Cuando veas esto avisame y lo hablamos.

2017-11-30 19:20 UTC, merged